# Generated by Django 5.2.5 on 2025-09-05 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postd', '0002_doctorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='postd.doctorprofile'),
        ),
    ]
