# Generated by Django 5.2.5 on 2025-09-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postd', '0010_treatment_patient_treatment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('pending', 'Pending')], default='active', max_length=20),
        ),
    ]
