# Generated by Django 5.2.5 on 2025-09-28 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postd', '0011_treatment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vitalreading',
            options={},
        ),
        migrations.CreateModel(
            name='PrescriptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postd.userprofile')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='postd.prescription')),
            ],
        ),
    ]
