from .openrouter_service import OpenRouterService
from typing import Dict, Any, List

class SuggestionEngine:
    """
    Suggestion engine that receives a resolved patient profile dict:
      {
        "patient_id": ...,
        "vitals": [...],
        "prescriptions": [...],
        "treatments": [...],
        "appointments": [...],
        "as_of": "2025-12-10T12:00:00"
      }
    Returns suggestions generated by OpenRouter AI.
    """
    def __init__(self, config: Dict[str, Any] = None):
        self.config = config or {}
        self.ai_service = OpenRouterService()

    def evaluate(self, profile: Dict[str, Any]) -> List[Dict[str, Any]]:
        # This engine now relies entirely on OpenRouter AI for suggestions.
        # It passes the full patient context to the AI model.
        return self.ai_service.generate_suggestions(profile)