# Generated by Django 5.2.5 on 2025-09-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postd', '0004_vitalreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalreading',
            name='diet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='exercise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='heartRate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
