# Generated by Django 5.2.5 on 2025-09-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postd', '0005_vitalreading_diet_vitalreading_exercise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitalreading',
            old_name='heartRate',
            new_name='heartrate',
        ),
    ]
