# Generated by Django 5.2.5 on 2025-09-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postd', '0012_notification_prescriptionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
