# Generated by Django 5.2.5 on 2025-10-09 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postd', '0013_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('missed_prescription', 'Missed Prescription'), ('critical_bp', 'Critical BP Reading'), ('general', 'General Notification')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='postd.userprofile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=255),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='postd_notification',
        ),
    ]
