# Generated by Django 5.2.5 on 2025-11-15 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postd', '0014_alter_notification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionlog',
            name='dose_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
