# Generated by Django 5.2.5 on 2025-11-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postd', '0015_prescriptionlog_dose_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescriptionlog',
            options={'ordering': ['-taken_at']},
        ),
        migrations.AddField(
            model_name='prescriptionlog',
            name='dose_label',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], default='morning', max_length=20),
        ),
    ]
