# Generated by Django 5.2.5 on 2025-12-12 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postd', '0017_availability_doctorslot_appointment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorslot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='doctorslot',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='postd.doctorprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(default='Hypertension follow-up'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='scheduled', max_length=20),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='DoctorSlot',
        ),
    ]
