# Generated by Django 5.2.5 on 2026-01-16 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postd', '0018_alter_doctorslot_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_systolic_threshold', models.IntegerField(default=140, help_text='Systolic BP threshold for warnings')),
                ('bp_diastolic_threshold', models.IntegerField(default=90, help_text='Diastolic BP threshold for warnings')),
                ('trend_slope_threshold', models.FloatField(default=0.5, help_text='Slope threshold for recognizing an increasing BP trend')),
                ('adherence_threshold', models.FloatField(default=0.8, help_text='Minimum adherence rate (0.0 - 1.0) before flagging issues')),
            ],
            options={
                'verbose_name': 'AI Suggestion Configuration',
                'verbose_name_plural': 'AI Suggestion Configuration',
            },
        ),
        migrations.CreateModel(
            name='AISuggestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('suggestions_generated', models.JSONField(help_text='Snapshot of the suggestions returned')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='postd.userprofile')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
