# Generated by Django 5.2.5 on 2026-01-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postd', '0019_aisuggestionconfig_aisuggestionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisuggestionconfig',
            name='preferred_ai_service',
            field=models.CharField(choices=[('openrouter', 'OpenRouter'), ('gemini', 'Gemini'), ('deepseek', 'DeepSeek')], default='openrouter', help_text='Primary AI service to use for suggestions', max_length=20),
        ),
    ]
