# Generated by Django 5.2.5 on 2026-01-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postd', '0020_aisuggestionconfig_preferred_ai_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisuggestionconfig',
            name='preferred_ai_service',
        ),
    ]
