// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIS3wMdGUWS_sAuxOpTbi4915j3RJ4mFc',
    appId: '1:89050977052:ios:f10b3bad4c892e7caaa0d9',
    messagingSenderId: '89050977052',
    projectId: 'boligrafo-final-project-2025',
    storageBucket: 'boligrafo-final-project-2025.firebasestorage.app',
    iosBundleId: 'com.example.boligrafo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSUOeM58NDIHO2-6Ek0k8O1uABRvEPJyM',
    appId: '1:89050977052:web:a8f7f837ce2a0ae3aaa0d9',
    messagingSenderId: '89050977052',
    projectId: 'boligrafo-final-project-2025',
    authDomain: 'boligrafo-final-project-2025.firebaseapp.com',
    storageBucket: 'boligrafo-final-project-2025.firebasestorage.app',
    measurementId: 'G-3WM0DH51D3',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFrWNibU-V-MktHZ14h9QL2ug1yVZjIrs',
    appId: '1:829295145279:web:4f490c7922abbd4427238a',
    messagingSenderId: '829295145279',
    projectId: 'boligrafo-final-year-project',
    authDomain: 'boligrafo-final-year-project.firebaseapp.com',
    storageBucket: 'boligrafo-final-year-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBrunPETCXKaNjgn1BMp3VzHqj9BOBlUs',
    appId: '1:829295145279:ios:6714114dac16be9b27238a',
    messagingSenderId: '829295145279',
    projectId: 'boligrafo-final-year-project',
    storageBucket: 'boligrafo-final-year-project.firebasestorage.app',
    iosBundleId: 'com.example.boligrafo',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNIxaHbCAvchQJMld28AXmH2qpWcf6GeI',
    appId: '1:829295145279:android:b2cb6843904e48ba27238a',
    messagingSenderId: '829295145279',
    projectId: 'boligrafo-final-year-project',
    storageBucket: 'boligrafo-final-year-project.firebasestorage.app',
  );

}