// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFrWNibU-V-MktHZ14h9QL2ug1yVZjIrs',
    appId: '1:829295145279:web:4f490c7922abbd4427238a',
    messagingSenderId: '829295145279',
    projectId: 'boligrafo-final-year-project',
    authDomain: 'boligrafo-final-year-project.firebaseapp.com',
    storageBucket: 'boligrafo-final-year-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNIxaHbCAvchQJMld28AXmH2qpWcf6GeI',
    appId: '1:829295145279:android:cb53799d38fc55ee27238a',
    messagingSenderId: '829295145279',
    projectId: 'boligrafo-final-year-project',
    storageBucket: 'boligrafo-final-year-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBrunPETCXKaNjgn1BMp3VzHqj9BOBlUs',
    appId: '1:829295145279:ios:b03652b6e21afbef27238a',
    messagingSenderId: '829295145279',
    projectId: 'boligrafo-final-year-project',
    storageBucket: 'boligrafo-final-year-project.firebasestorage.app',
    iosBundleId: 'com.example.webApp',
  );
}
